### PR TITLE
添加明星衣橱

### PR DESCRIPTION
**Pull request by lilydjwg**
这是我上家公司，也是把我坑得最惨的一家。

### CODE REVIEW

**Comment by brunobell** [comment]
I now understand why lilydjwg once said she'd been in a very tough time... Sure these companies should be blacklisted!

**Comment by shengxinjing** [comment]
冲突了

**Comment by lilydjwg** [comment]
冲突已解决。

**Comment by ly0** [comment]
@lilydjwg 依云酱 依云酱！

**Pull request merged**
